package iptables

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"sync"

	"github.com/tui-tools/tui-firewall/internal/firewall"
	"github.com/tui-tools/tui-firewall/internal/nftables/staging"
)

// demoV4 is the IPv4 ruleset --demo=iptables shows: the shape of a stock cloud
// image (Oracle Cloud's Ubuntu, for one), where iptables-persistent restores
// an INPUT chain that ends in a REJECT, docker has added its chains, and the
// provider's metadata services have a chain of their own. It is the case this
// backend was written for, and the one where appending a rule is a bug.
const demoV4 = `# Generated by iptables-save v1.8.10 (nf_tables)
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [182664:61318224]
:DOCKER - [0:0]
:DOCKER-BRIDGE - [0:0]
:DOCKER-CT - [0:0]
:DOCKER-FORWARD - [0:0]
:DOCKER-INTERNAL - [0:0]
:DOCKER-USER - [0:0]
:InstanceServices - [0:0]
[141208:331042817] -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
[12:1008] -A INPUT -p icmp -j ACCEPT
[2811:268902] -A INPUT -i lo -j ACCEPT
[97:5820] -A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
[3620:212314] -A INPUT -j REJECT --reject-with icmp-host-prohibited
[0:0] -A FORWARD -j DOCKER-USER
[0:0] -A FORWARD -j DOCKER-FORWARD
[0:0] -A FORWARD -j REJECT --reject-with icmp-host-prohibited
[51711:3802005] -A OUTPUT -d 169.254.0.0/16 -j InstanceServices
[0:0] -A DOCKER ! -i docker0 -o docker0 -j DROP
[0:0] -A DOCKER-BRIDGE -o docker0 -j DOCKER
[0:0] -A DOCKER-CT -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
[0:0] -A DOCKER-FORWARD -j DOCKER-CT
[0:0] -A DOCKER-FORWARD -j DOCKER-INTERNAL
[0:0] -A DOCKER-FORWARD -j DOCKER-BRIDGE
[0:0] -A DOCKER-FORWARD -i docker0 -j ACCEPT
[0:0] -A InstanceServices -d 169.254.0.2/32 -p tcp -m owner --uid-owner 0 -m tcp --dport 3260 -m comment --comment "metadata iSCSI" -j ACCEPT
[4412:264720] -A InstanceServices -d 169.254.169.254/32 -p udp -m udp --dport 53 -m comment --comment "metadata DNS" -j ACCEPT
[21:1260] -A InstanceServices -d 169.254.169.254/32 -p tcp -m tcp --dport 80 -m comment --comment "metadata HTTP" -j ACCEPT
[980:74480] -A InstanceServices -d 169.254.169.254/32 -p udp -m udp --dport 123 -m comment --comment "metadata NTP" -j ACCEPT
[0:0] -A InstanceServices -d 169.254.0.0/16 -p tcp -m tcp -j REJECT --reject-with tcp-reset
[0:0] -A InstanceServices -d 169.254.0.0/16 -p udp -m udp -j REJECT --reject-with icmp-port-unreachable
COMMIT
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:DOCKER - [0:0]
[0:0] -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
[0:0] -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
[0:0] -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
COMMIT
`

// demoV6 is the IPv6 half: the cloud image leaves it open, and docker has
// added its forwarding hooks.
const demoV6 = `# Generated by ip6tables-save v1.8.10 (nf_tables)
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:DOCKER-FORWARD - [0:0]
:DOCKER-USER - [0:0]
[0:0] -A FORWARD -j DOCKER-USER
[0:0] -A FORWARD -j DOCKER-FORWARD
COMMIT
`

// Fake is an in-memory iptables used by --demo=iptables and the tests. It
// applies the very commands the real backend builds — iptables -I/-D/-P, the
// staged iptables-restore scripts, netfilter-persistent save — to its own
// dumps, so the UI and the builders cannot tell it from a machine.
type Fake struct {
	mu    sync.Mutex
	state State
	// Log records every command that was run, in order.
	Log []firewall.Command
	// FailWith, when set, makes the next Run fail with this error.
	FailWith error
}

// NewFake returns a Fake preloaded with the cloud-image ruleset, saved and in
// sync, under the Debian persistence layout.
func NewFake() *Fake {
	f, err := NewFakeFrom(demoV4, demoV6)
	if err != nil {
		// The demo ruleset is a constant; failing to parse it is a bug.
		panic(err)
	}
	return f
}

// NewFakeFrom builds a Fake from two iptables-save dumps, with the saved
// files equal to them.
func NewFakeFrom(v4, v6 string) (*Fake, error) {
	d4, err := ParseSave(V4, v4)
	if err != nil {
		return nil, err
	}
	d6, err := ParseSave(V6, v6)
	if err != nil {
		return nil, err
	}
	f := &Fake{state: State{V4: d4, V6: d6, HasV6: true}}
	layout := netfilterPersistentLayout
	layout.Enabled = true
	f.state.Persistence.Layout = layout
	f.saveLocked()
	return f, nil
}

// Name identifies the backend.
func (f *Fake) Name() string { return "demo" }

// Describe names the backend for the status line.
func (f *Fake) Describe() string { return "demo iptables (no changes are applied)" }

// Capabilities mirrors the real backend.
func (f *Fake) Capabilities() firewall.Capabilities { return capabilities }

// Preview renders the change as the real backend would, without a privilege
// prefix: the demo never escalates.
func (f *Fake) Preview(change firewall.Change) string { return change.String() }

// Load returns the model of the in-memory state.
func (f *Fake) Load(_ context.Context) (firewall.Model, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.state.Persistence.Drift = ComputeDrift(f.state)
	return Model(f.state), nil
}

// State returns a copy of the in-memory state.
func (f *Fake) State() State {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.state.Persistence.Drift = ComputeDrift(f.state)
	return cloneState(f.state)
}

// PersistState is the persistence part of the state, for the header.
func (f *Fake) PersistState() Persistence { return f.State().Persistence }

// Run applies a change, command by command, stopping at the first failure.
func (f *Fake) Run(_ context.Context, change firewall.Change) (string, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.FailWith != nil {
		err := f.FailWith
		f.FailWith = nil
		return "", err
	}
	var outputs []string
	for _, cmd := range change.Commands {
		f.Log = append(f.Log, cmd)
		out, err := f.apply(cmd)
		if out != "" {
			outputs = append(outputs, out)
		}
		if err != nil {
			return strings.Join(outputs, "\n"), err
		}
	}
	return strings.Join(outputs, "\n"), nil
}

// apply runs one command against the in-memory state.
func (f *Fake) apply(cmd firewall.Command) (string, error) {
	if len(cmd.Argv) == 0 {
		return "", errorf("empty command")
	}
	switch cmd.Argv[0] {
	case V4.Binary(), V6.Binary():
		family := familyOfBinary(cmd.Argv[0])
		dump := f.dumpPtr(family)
		return "", applyCommand(dump, cmd.Argv[1:])
	case V4.RestoreBinary(), V6.RestoreBinary():
		family := familyOfBinary(strings.TrimSuffix(cmd.Argv[0], "-restore"))
		noflush := len(cmd.Argv) > 1 && cmd.Argv[1] == "--noflush"
		return "", f.restore(family, cmd.Stdin, noflush)
	case "netfilter-persistent":
		if len(cmd.Argv) > 1 && cmd.Argv[1] == "save" {
			f.saveLocked()
			return "run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save\n" +
				"run-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save", nil
		}
	case iptablesInit, ip6tablesInit:
		f.saveLocked()
		return "iptables: Saving firewall rules to /etc/sysconfig/iptables: [  OK  ]", nil
	}
	return "", errorf("%s is not something the demo applies", cmd.String())
}

// familyOfBinary maps iptables/ip6tables to its family.
func familyOfBinary(bin string) Family {
	if bin == V6.Binary() {
		return V6
	}
	return V4
}

// dumpPtr returns the running dump of a family. The caller holds f.mu.
func (f *Fake) dumpPtr(family Family) *Dump {
	if family == V6 {
		return &f.state.V6
	}
	return &f.state.V4
}

// saveLocked copies the running rules to the saved files, counters dropped the
// way iptables-save without -c drops them. The caller holds f.mu.
func (f *Fake) saveLocked() {
	v4 := stripCounters(cloneDump(f.state.V4))
	v6 := stripCounters(cloneDump(f.state.V6))
	f.state.Persistence.SavedV4 = &v4
	f.state.Persistence.SavedV6 = &v6
}

// restore applies an iptables-restore input: with --noflush, each rule line is
// a command against the running tables; without, each table the input names
// replaces the running one. Either way it is all-or-nothing, like the real
// command: a failing line leaves the state as it was.
func (f *Fake) restore(family Family, stdin string, noflush bool) error {
	dump := f.dumpPtr(family)
	work := cloneDump(*dump)
	if !noflush {
		loaded, err := ParseSave(family, stdin)
		if err != nil {
			return err
		}
		for _, table := range loaded.Tables {
			replaced := false
			for i := range work.Tables {
				if work.Tables[i].Name == table.Name {
					work.Tables[i] = table
					replaced = true
				}
			}
			if !replaced {
				work.Tables = append(work.Tables, table)
			}
		}
		*dump = work
		return nil
	}
	for n, raw := range strings.Split(stdin, "\n") {
		line := strings.TrimSpace(raw)
		switch {
		case line == "", strings.HasPrefix(line, "#"), line == "COMMIT":
			continue
		case strings.HasPrefix(line, "*"):
			if line != "*"+TableFilter {
				return errorf("the demo restores the filter table only, not %s", line)
			}
			continue
		}
		args, err := SplitArgs(line)
		if err != nil {
			return err
		}
		if err := applyCommand(&work, args); err != nil {
			return fmt.Errorf("%s-restore: line %d failed: %w", family.Binary(), n+1, err)
		}
	}
	*dump = work
	return nil
}

// applyCommand applies one iptables command (without the binary) to the filter
// table of a dump: -I CHAIN [N] spec, -A CHAIN spec, -D CHAIN spec|N, -P CHAIN
// TARGET — the verbs this backend builds.
func applyCommand(dump *Dump, args []string) error {
	if len(args) < 2 {
		return errorf("the demo needs a verb and a chain: %q", strings.Join(args, " "))
	}
	verb, chainName, rest := args[0], args[1], args[2:]
	table := ensureFilter(dump)
	chain := findChainPtr(table, chainName)
	if chain == nil {
		return errorf("%s: No chain/target/match by that name", chainName)
	}
	switch verb {
	case "-P":
		if len(rest) != 1 || (rest[0] != TargetAccept && rest[0] != TargetDrop) {
			return errorf("bad policy %q", strings.Join(rest, " "))
		}
		if !chain.Builtin() {
			return errorf("cannot set a policy on user chain %s", chainName)
		}
		chain.Policy = rest[0]
		return nil
	case "-A", "-I":
		position := len(chain.Rules) + 1
		if verb == "-I" {
			position = 1
			if len(rest) > 0 && isNumber(rest[0]) {
				position, _ = strconv.Atoi(rest[0])
				rest = rest[1:]
			}
		}
		if position < 1 || position > len(chain.Rules)+1 {
			return errorf("Index of insertion too big.")
		}
		spec := JoinArgs(rest)
		rule := Rule{Chain: chainName, Spec: spec, Args: append([]string(nil), rest...),
			Counter: &Counter{}, Match: decodeArgs(rest)}
		chain.Rules = append(chain.Rules[:position-1],
			append([]Rule{rule}, chain.Rules[position-1:]...)...)
		renumber(chain)
		return nil
	case "-D":
		if len(rest) == 1 && isNumber(rest[0]) {
			n, _ := strconv.Atoi(rest[0])
			if n < 1 || n > len(chain.Rules) {
				return errorf("Index of deletion too big.")
			}
			chain.Rules = append(chain.Rules[:n-1], chain.Rules[n:]...)
			renumber(chain)
			return nil
		}
		want := JoinArgs(rest)
		for i, rule := range chain.Rules {
			if JoinArgs(rule.Args) == want {
				chain.Rules = append(chain.Rules[:i], chain.Rules[i+1:]...)
				renumber(chain)
				return nil
			}
		}
		return errorf("Bad rule (does a matching rule exist in that chain?).")
	default:
		return errorf("the demo does not apply %s", verb)
	}
}

// ensureFilter returns the filter table of a dump, creating it with its three
// built-in chains the way the kernel would on first use.
func ensureFilter(dump *Dump) *Table {
	for i := range dump.Tables {
		if dump.Tables[i].Name == TableFilter {
			return &dump.Tables[i]
		}
	}
	dump.Tables = append([]Table{{Name: TableFilter, Chains: []Chain{
		{Name: ChainInput, Policy: TargetAccept},
		{Name: ChainForward, Policy: TargetAccept},
		{Name: ChainOutput, Policy: TargetAccept},
	}}}, dump.Tables...)
	return &dump.Tables[0]
}

// findChainPtr returns the named chain of a table.
func findChainPtr(table *Table, name string) *Chain {
	for i := range table.Chains {
		if table.Chains[i].Name == name {
			return &table.Chains[i]
		}
	}
	return nil
}

// renumber rewrites the 1-based positions after a change.
func renumber(chain *Chain) {
	for i := range chain.Rules {
		chain.Rules[i].Index = i + 1
	}
}

// cloneDump deep-copies a dump.
func cloneDump(d Dump) Dump {
	out := d
	out.Warnings = append([]string(nil), d.Warnings...)
	out.Tables = make([]Table, len(d.Tables))
	for i, t := range d.Tables {
		nt := Table{Name: t.Name, Chains: make([]Chain, len(t.Chains))}
		for j, c := range t.Chains {
			nc := c
			nc.Rules = make([]Rule, len(c.Rules))
			for k, r := range c.Rules {
				nr := r
				nr.Args = append([]string(nil), r.Args...)
				if r.Counter != nil {
					counter := *r.Counter
					nr.Counter = &counter
				}
				nc.Rules[k] = nr
			}
			nt.Chains[j] = nc
		}
		out.Tables[i] = nt
	}
	return out
}

// stripCounters drops the counters of a dump.
func stripCounters(d Dump) Dump {
	for i := range d.Tables {
		for j := range d.Tables[i].Chains {
			for k := range d.Tables[i].Chains[j].Rules {
				d.Tables[i].Chains[j].Rules[k].Counter = nil
			}
		}
	}
	return d
}

// cloneState deep-copies a state.
func cloneState(s State) State {
	out := s
	out.V4 = cloneDump(s.V4)
	out.V6 = cloneDump(s.V6)
	if s.Persistence.SavedV4 != nil {
		d := cloneDump(*s.Persistence.SavedV4)
		out.Persistence.SavedV4 = &d
	}
	if s.Persistence.SavedV6 != nil {
		d := cloneDump(*s.Persistence.SavedV6)
		out.Persistence.SavedV6 = &d
	}
	return out
}

// SnapshotRuleset serialises the filter tables so the demo can restore them on
// a staged rollback, in the same restore format the real backend captures.
func (f *Fake) SnapshotRuleset(_ context.Context) (string, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	return JoinSnapshot(renderFilter(f.state.V4), renderFilter(f.state.V6)), nil
}

// renderFilter renders only the filter table of a dump as a restore file.
func renderFilter(d Dump) string {
	only := Dump{Family: d.Family}
	if t, ok := d.Table(TableFilter); ok {
		only.Tables = []Table{t}
	}
	return Render(only, "")
}

// StagingDialect is the same dialect the real backend uses.
func (f *Fake) StagingDialect() staging.Dialect { return Dialect{HasV6: true} }

// PreparePersist builds the persist change and its diff, like the real one.
func (f *Fake) PreparePersist(_ context.Context) (firewall.Change, string, error) {
	state := f.State()
	change, err := BuildPersist(state)
	if err != nil {
		return firewall.Change{}, "", err
	}
	return change, PersistDiff(state), nil
}

// BuildAddRule creates a rule in the chain the group names.
func (f *Fake) BuildAddRule(group string, spec firewall.RuleSpec) (firewall.Change, error) {
	return f.State().BuildAddRule(group, spec)
}

// BuildDeleteRule removes the selected rule.
func (f *Fake) BuildDeleteRule(group string, rule firewall.Rule) (firewall.Change, error) {
	return f.State().BuildDeleteRule(group, rule)
}

// BuildSetEnabled refuses, like the real backend.
func (f *Fake) BuildSetEnabled(enabled bool) (firewall.Change, error) {
	return (&Real{}).BuildSetEnabled(enabled)
}

// BuildReload refuses, like the real backend.
func (f *Fake) BuildReload() (firewall.Change, error) { return (&Real{}).BuildReload() }

// BuildSetPolicy changes the policy of the chain a group shows.
func (f *Fake) BuildSetPolicy(group string, _ firewall.PolicyDirection,
	policy firewall.Policy) (firewall.Change, error) {
	return f.State().BuildSetPolicy(group, policy)
}

// BuildSetLogging refuses, like the real backend.
func (f *Fake) BuildSetLogging(level string) (firewall.Change, error) {
	return (&Real{}).BuildSetLogging(level)
}

// Extras reports that iptables has no actions beyond the common set.
func (f *Fake) Extras(_ firewall.Model, _ string) []firewall.Extra { return nil }

// BuildExtra always fails.
func (f *Fake) BuildExtra(_, id string, _ []string) (firewall.Change, error) {
	return firewall.Change{}, errorf("no extra action %q", id)
}
