package iptables

import (
	"reflect"
	"strings"
	"testing"
)

func TestParseSaveReadsTheCloudImage(t *testing.T) {
	dump, err := ParseSave(V4, fixture(t, "oci-iptables-save.txt"))
	if err != nil {
		t.Fatalf("ParseSave: %v", err)
	}
	if dump.Version != "1.8.10" || dump.Variant != "nf_tables" {
		t.Errorf("version/variant = %q/%q, want 1.8.10/nf_tables", dump.Version, dump.Variant)
	}
	var names []string
	for _, table := range dump.Tables {
		names = append(names, table.Name)
	}
	if !reflect.DeepEqual(names, []string{"mangle", "filter", "nat"}) {
		t.Errorf("tables = %v", names)
	}
	input, ok := dump.Chain(TableFilter, ChainInput)
	if !ok {
		t.Fatal("no INPUT chain")
	}
	if len(input.Rules) != 9 || input.Policy != TargetAccept {
		t.Fatalf("INPUT = %d rules, policy %q; want 9, ACCEPT", len(input.Rules), input.Policy)
	}
	at, rule := input.CatchAll()
	if at != 9 || rule.Match.Target != TargetReject {
		t.Errorf("catch-all = %d (%+v), want rule 9, a REJECT", at, rule.Match)
	}
	if got := rule.Match.TargetDetail(); got != "-j REJECT --reject-with icmp-host-prohibited" {
		t.Errorf("target detail = %q", got)
	}
	// The counter prefix is read, and not part of the rule's identity.
	if input.Rules[0].Counter == nil || strings.HasPrefix(input.Rules[0].Spec, "[") {
		t.Errorf("first rule = %+v: counter not split from the spec", input.Rules[0])
	}
	// The jump into tailscale's chain is a jump, not a verdict.
	if input.Rules[0].Match.Target != "ts-input" || input.Rules[0].Match.Terminal() {
		t.Errorf("rule 1 = %+v, want a jump to ts-input", input.Rules[0].Match)
	}
}

func TestParseSaveKeepsAQuotedCommentAsOneWord(t *testing.T) {
	dump, err := ParseSave(V4, fixture(t, "oci-iptables-save.txt"))
	if err != nil {
		t.Fatalf("ParseSave: %v", err)
	}
	chain, _ := dump.Chain(TableFilter, "InstanceServices")
	if len(chain.Rules) == 0 {
		t.Fatal("InstanceServices is empty")
	}
	m := chain.Rules[0].Match
	if !strings.HasPrefix(m.Comment, "See the Oracle-Provided Images section") {
		t.Errorf("comment = %q", m.Comment)
	}
	if m.Dst != "169.254.0.2/32" || m.Proto != "tcp" || m.DPort != "3260" {
		t.Errorf("match = %+v", m)
	}
	// -m owner has no column: it is kept as text rather than dropped.
	if !reflect.DeepEqual(m.Unmodeled, []string{"-m owner", "--uid-owner 0"}) {
		t.Errorf("unmodeled = %q", m.Unmodeled)
	}
}

func TestParseSaveNegations(t *testing.T) {
	dump, err := ParseSave(V4, fixture(t, "oci-iptables-save.txt"))
	if err != nil {
		t.Fatalf("ParseSave: %v", err)
	}
	chain, _ := dump.Chain(TableFilter, "DOCKER")
	m := chain.Rules[0].Match
	if m.InIface != "!docker0" || m.OutIface != "docker0" || m.Target != TargetDrop {
		t.Errorf("docker isolation rule = %+v", m)
	}
}

func TestParseSaveRoundTripsThroughComparable(t *testing.T) {
	// Rendering and re-reading a dump must give back the same rules: the
	// fake and the persist diff both rely on it.
	dump, err := ParseSave(V4, fixture(t, "oci-iptables-save.txt"))
	if err != nil {
		t.Fatalf("ParseSave: %v", err)
	}
	again, err := ParseSave(V4, Comparable(dump))
	if err != nil {
		t.Fatalf("re-parsing: %v", err)
	}
	if Comparable(again) != Comparable(dump) {
		t.Errorf("round trip changed the dump:\n%s\n---\n%s", Comparable(dump), Comparable(again))
	}
}

func TestParseSaveRejectsABrokenDump(t *testing.T) {
	for name, text := range map[string]string{
		"rule outside a table": "-A INPUT -j ACCEPT\n",
		"never committed":      "*filter\n:INPUT ACCEPT [0:0]\n",
		"bad chain line":       "*filter\n:INPUT\nCOMMIT\n",
		"bad counter":          "*filter\n:INPUT ACCEPT [0:0]\n[x:1] -A INPUT -j ACCEPT\nCOMMIT\n",
		"unterminated quote":   "*filter\n:INPUT ACCEPT [0:0]\n-A INPUT -m comment --comment \"oops -j ACCEPT\nCOMMIT\n",
	} {
		if _, err := ParseSave(V4, text); err == nil {
			t.Errorf("%s: expected an error", name)
		}
	}
}

func TestParseSaveReportsLegacyTablesWarning(t *testing.T) {
	text := "# Generated by iptables-save v1.8.10 (nf_tables)\n*filter\n" +
		":INPUT ACCEPT [0:0]\nCOMMIT\n" +
		"# Warning: iptables-legacy tables present, use iptables-legacy-save to see them\n"
	dump, err := ParseSave(V4, text)
	if err != nil {
		t.Fatalf("ParseSave: %v", err)
	}
	model := Model(State{V4: dump})
	if !strings.Contains(model.Warning, "iptables-legacy tables") {
		t.Errorf("warning = %q, want the legacy tables named", model.Warning)
	}
}

func TestSplitAndQuoteArgs(t *testing.T) {
	args, err := SplitArgs(`-m comment --comment "two \"quoted\" words" -j ACCEPT`)
	if err != nil {
		t.Fatalf("SplitArgs: %v", err)
	}
	want := []string{"-m", "comment", "--comment", `two "quoted" words`, "-j", "ACCEPT"}
	if !reflect.DeepEqual(args, want) {
		t.Fatalf("args = %q", args)
	}
	if got := JoinArgs(args); got != `-m comment --comment "two \"quoted\" words" -j ACCEPT` {
		t.Errorf("JoinArgs = %s", got)
	}
}

// TestCommentWithSpacesSurvivesRestore covers the comments the add form now
// accepts: a space, parentheses and a single quote must come back as one word
// from the dump line a staged batch or a save writes.
func TestCommentWithSpacesSurvivesRestore(t *testing.T) {
	argv := []string{"-A", "INPUT", "-p", "tcp", "--dport", "19443",
		"-m", "comment", "--comment", "headscale control (tailnet) it's", "-j", "ACCEPT"}
	got, err := SplitArgs(JoinArgs(argv))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Join(got, "|") != strings.Join(argv, "|") {
		t.Errorf("round trip = %q, want %q", got, argv)
	}
}
